### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by SeanGuoXuan** [googlecartographer/async_grpc#48]
Hi All,
I am using ubuntu 18.04 with ros melodic. I add async_grpc to src directory. When I compile using 
catkin_make_isolated --install --use-ninja, I got the following errors:

[68/390] Building CXX object CMakeFiles/cartographer.dir/cartographer/cloud/client/map_builder_stub.cc.o
FAILED: CMakeFiles/cartographer.dir/cartographer/cloud/client/map_builder_stub.cc.o 
/usr/bin/c++  -DGFLAGS_IS_A_DLL=0 -isystem /usr/include/eigen3 -isystem /home/sean/sean/cartographer_ws/install_isolated/include -isystem /usr/include/lua5.2 -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/local/include -I. -I/home/sean/sean/cartographer_ws/src/cartographer -O3 -DNDEBUG    -pthread -std=c++11 -fPIC  -Wall -Wpedantic -Werror=format-security -Werror=missing-braces -Werror=reorder -Werror=return-type -Werror=switch -Werror=uninitialized -O3 -DNDEBUG -MD -MT CMakeFiles/cartographer.dir/cartographer/cloud/client/map_builder_stub.cc.o -MF CMakeFiles/cartographer.dir/cartographer/cloud/client/map_builder_stub.cc.o.d -o CMakeFiles/cartographer.dir/cartographer/cloud/client/map_builder_stub.cc.o -c /home/sean/sean/cartographer_ws/src/cartographer/cartographer/cloud/client/map_builder_stub.cc
/home/sean/sean/cartographer_ws/src/cartographer/cartographer/cloud/client/map_builder_stub.cc: In member function ‘virtual int cartographer::cloud::MapBuilderStub::AddTrajectoryBuilder(const std::set<cartographer::mapping::TrajectoryBuilderInterface::SensorId>&, const cartographer::mapping::proto::TrajectoryBuilderOptions&, cartographer::mapping::MapBuilderInterface::LocalSlamResultCallback)’:
/home/sean/sean/cartographer_ws/src/cartographer/cartographer/cloud/client/map_builder_stub.cc:64:66: error: no matching function for call to ‘async_grpc::Client<cartographer::cloud::handlers::AddTrajectorySignature>::Client(std::shared_ptr<grpc::Channel>&, async_grpc::RetryStrategy)’
                            common::FromMilliseconds(100), 2.f, 5));
                                                                  ^
In file included from /home/sean/sean/cartographer_ws/src/cartographer/cartographer/cloud/internal/client/trajectory_builder_stub.h:22:0,
                 from /home/sean/sean/cartographer_ws/src/cartographer/cartographer/cloud/client/map_builder_stub.cc:20:
/home/sean/sean/cartographer_ws/install_isolated/include/async_grpc/client.h:60:3: note: candidate: async_grpc::Client<RpcServiceMethodConcept, (grpc::internal::RpcMethod::RpcType)0>::Client(std::shared_ptr<grpc::Channel>, async_grpc::common::Duration, async_grpc::RetryStrategy) [with RpcServiceMethodConcept = cartographer::cloud::handlers::AddTrajectorySignature; async_grpc::common::Duration = std::chrono::duration<long int, std::ratio<1, 10000000> >; async_grpc::RetryStrategy = std::function<async_grpc::common::optional<std::chrono::duration<long int, std::ratio<1, 10000000> > >(int, const grpc::Status&)>]
   Client(std::shared_ptr<::grpc::Channel> channel, common::Duration timeout,
   ^~~~~~
/home/sean/sean/cartographer_ws/install_isolated/include/async_grpc/client.h:60:3: note:   no known conversion for argument 2 from ‘async_grpc::RetryStrategy {aka std::function<async_grpc::common::optional<std::chrono::duration<long int, std::ratio<1, 10000000> > >(int, const grpc::Status&)>}’ to ‘async_grpc::common::Duration {aka std::chrono::duration<long int, std::ratio<1, 10000000> >}’
/home/sean/sean/cartographer_ws/install_isolated/include/async_grpc/client.h:51:3: note: candidate: async_grpc::Client<RpcServiceMethodConcept, (grpc::internal::RpcMethod::RpcType)0>::Client(std::shared_ptr<grpc::Channel>) [with RpcServiceMethodConcept = cartographer::cloud::handlers::AddTrajectorySignature]
   Client(std::shared_ptr<::grpc::Channel> channel)
   ^~~~~~
/home/sean/sean/cartographer_ws/install_isolated/include/async_grpc/client.h:51:3: note:   candidate expects 1 argument, 2 provided
/home/sean/sean/cartographer_ws/install_isolated/include/async_grpc/client.h:45:7: note: candidate: async_grpc::Client<cartographer::cloud::handlers::AddTrajectorySignature>::Client(async_grpc::Client<cartographer::cloud::handlers::AddTrajectorySignature>&&)
 class Client<RpcServiceMethodConcept, ::grpc::internal::RpcMethod::NORMAL_RPC> {
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sean/sean/cartographer_ws/install_isolated/include/async_grpc/client.h:45:7: note:   candidate expects 1 argument, 2 provided
/home/sean/sean/cartographer_ws/src/cartographer/cartographer/cloud/client/map_builder_stub.cc: In member function ‘virtual int cartographer::cloud::MapBuilderStub::AddTrajectoryForDeserialization(const cartographer::mapping::proto::TrajectoryBuilderOptionsWithSensorIds&)’:
/home/sean/sean/cartographer_ws/src/cartographer/cartographer/cloud/client/map_builder_stub.cc:81:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
/home/sean/sean/cartographer_ws/src/cartographer/cartographer/cloud/client/map_builder_stub.cc: In member function ‘virtual const std::vector<cartographer::mapping::proto::TrajectoryBuilderOptionsWithSensorIds>& cartographer::cloud::MapBuilderStub::GetAllTrajectoryBuilderOptions() const’:
/home/sean/sean/cartographer_ws/src/cartographer/cartographer/cloud/client/map_builder_stub.cc:171:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: some warnings being treated as errors
[73/390] Building CXX object CMakeFiles/cartographer.cloud.internal.handlers.add_t...ler_test.dir/cartographer/cloud/internal/handlers/add_trajectory_handler_test.cc.o
ninja: build stopped: subcommand failed.
<== Failed to process package 'cartographer': 
  Command '['/home/sean/sean/cartographer_ws/install_isolated/env.sh', 'ninja', '-j8', '-l8']' returned non-zero exit status 1

Also, I notice file: src/cartographer/cartographer/cloud/client/map_builder_stub.cc has incomplete method:
const std::vector<mapping::proto::TrajectoryBuilderOptionsWithSensorIds>&
  MapBuilderStub::GetAllTrajectoryBuilderOptions() const {
     LOG(FATAL) << "Not implemented";
}
So, is this package still under development? And this is causing compiling fails?

,

**Comment by Fxx0105** [comment]
I have the same problem， did you solve the problem？
